version: '3.5'

services:
  web:
    image: nginx:latest
    container_name: web
    restart: always
    environment:
      TZ: 'Asia/Tokyo'
    ports:
      - "80:80"
    volumes:
      - ./docker/local/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./web:/var/www/html

  app:
    build: ./docker/local/php-fpm
    container_name: app
    volumes:
      - ./web:/var/www/html
      - ./docker/local/php-fpm/php.ini:/usr/local/etc/php/php.ini

  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/local/mysql/etc-mysql.cnf:/etc/mysql/conf.d/etc-mysql.cnf
      - ./db-data:/var/lib/mysql
      - ./docker/local/mysql/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    links:
      - mysql
    ports:
      - 8080:80
    volumes:
      - /sessions
  watch:
    image: node:12
    container_name: watch
    working_dir: /home/app
    command: "npm run watch"
    volumes:
      - ./web:/home/app